version: "3.9"
services:
  app:
    build: .
    ports:
      - "80:80"
      - "25565:25565"
      - "25575:25575"
    volumes:
      - type: bind
        source: ./scripts/script_dependencies
        target: /app/scripts/script_dependencies
    restart: always
