version: "3.9"
services:
  app:
    build: .
    ports:
      - "80:3000"
      - "25565:25565"
    volumes:
      - script_dependencies:/app/scripts/script_dependencies
volumes:
  script_dependencies:
    external: false
