version: "3.9"
services:
  app:
    build: .
    ports:
      - "80:3000"
      - "25565:25565"
      - "25575:25575"
    volumes:
            - type: bind
              source: /home/script_dependencies
              target: /app/scripts/script_dependencies
